/**
 * Created by Window on 5/15/2017.
 */
import  {Component, AfterViewInit} from '@angular/core';

import  { Todo } from '../item/todo';

@Component({
    selector: 'todo-list',
    template : `
                <todo-input (onAddTodoItem)="add($event)" ></todo-input>
                <h1>This is your to do list items</h1> 
                 <ul>
                    <li *ngFor="let item of getAll()"><todo-item (onChange)="remove($event)" [data]="item"></todo-item></li>
                </ul>`

})


export  class TodoListComponent  implements AfterViewInit{
    public  todoItems : Todo[] = [];
    constructor(){}

    ngAfterViewInit(){
        //this.autoGenerateData();
    }

    add(todo : Todo){
        this.todoItems.push(todo);
    }
    remove(todo : Todo ){
        this.todoItems.splice(this.todoItems.indexOf(todo),1);
    }

    getAll(){
        return this.todoItems;
    }



    autoGenerateData(){
        this.todoItems = [
            {
                title : 'item 1',
                completed : false
            },
            {
                title : 'item 2',
                completed: true
            }
        ]
    }
}